apiVersion: v2
name: alluredeck
description: Allure Reports Dashboard
type: application
version: 0.1.0
appVersion: "0.1.2"
home: https://github.com/mkutlak/alluredeck
sources:
  - https://github.com/mkutlak/alluredeck
maintainers:
  - name: mkutlak
keywords:
  - allure
  - testing
  - reports
  - dashboard
