apiVersion: v2
name: alluredeck
description: Allure Reports Dashboard
type: application
version: 0.10.0
appVersion: "0.14.0"
home: https://github.com/mkutlak/alluredeck
sources:
  - https://github.com/mkutlak/alluredeck
maintainers:
  - name: mkutlak
keywords:
  - allure
  - testing
  - reports
  - dashboard
annotations:
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/mkutlak/alluredeck
