services:
  alluredeck-ui:
    image: alluredeck-ui:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    environment:
      VITE_API_URL: "${VITE_API_URL:-http://localhost:5050/api/v1}"
      VITE_APP_TITLE: "${VITE_APP_TITLE:-AllureDeck}"
    ports:
      - "7474:8080"
    depends_on:
      - allure-api
    restart: unless-stopped

  allure-api:
    image: alluredeck-api:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      SECURITY_ENABLED: "1"
      SECURITY_USER: "${SECURITY_USER:-admin}"
      SECURITY_PASS: "${SECURITY_PASS:-admin}"
      SECURITY_VIEWER_USER: "${SECURITY_VIEWER_USER:-viewer}"
      SECURITY_VIEWER_PASS: "${SECURITY_VIEWER_PASS:-viewer}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY:-68af59c5a580cf01e094ff4cf6722203c6e2a6de6ed6c3fb8185bfac9c490f3e}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS:-http://localhost:7474}"
      KEEP_HISTORY: "1"
      KEEP_HISTORY_LATEST: "20"
      CHECK_RESULTS_EVERY_SECONDS: "NONE"
      GOMEMLIMIT: "1GiB"
    ports:
      - "5050:8080"
    volumes:
      - allure-projects:/app/projects
    restart: unless-stopped

volumes:
  allure-projects:
