{{- if .Values.ui.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alluredeck.ui.fullname" . }}
  labels:
    {{- include "alluredeck.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ui.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{- range .Values.ui.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ui.ingress.host }}
    - host: {{ .Values.ui.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ui.ingress.path }}
            pathType: {{ .Values.ui.ingress.pathType }}
            backend:
              service:
                name: {{ include "alluredeck.ui.fullname" . }}
                port:
                  name: http-ui
    {{- end }}
{{- end }}
{{- if .Values.api.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alluredeck.api.fullname" . }}
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.ingress.ingressClassName }}
  ingressClassName: {{ .Values.api.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.api.ingress.host }}
    - host: {{ .Values.api.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: {{ .Values.api.ingress.pathType }}
            backend:
              service:
                name: {{ include "alluredeck.api.fullname" . }}
                port:
                  name: http-api
    {{- end }}
{{- end }}
