{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alluredeck.fullname" . }}
  labels:
    {{- include "alluredeck.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path }}
            pathType: {{ .Values.ingress.api.pathType }}
            backend:
              service:
                name: {{ include "alluredeck.api.fullname" . }}
                port:
                  name: http-api
          {{- if .Values.ingress.swagger.enabled }}
          - path: {{ .Values.ingress.swagger.path }}
            pathType: {{ .Values.ingress.swagger.pathType }}
            backend:
              service:
                name: {{ include "alluredeck.api.fullname" . }}
                port:
                  name: http-api
          {{- end }}
          - path: {{ .Values.ingress.ui.path }}
            pathType: {{ .Values.ingress.ui.pathType }}
            backend:
              service:
                name: {{ include "alluredeck.ui.fullname" . }}
                port:
                  name: http-ui
    {{- end }}
{{- end }}
