{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alluredeck.api.serviceAccountName" . }}
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.serviceAccount.ui.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alluredeck.ui.serviceAccountName" . }}
  labels:
    {{- include "alluredeck.ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
