ALTER TABLE builds ADD COLUMN flaky_count      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN retried_count    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN new_failed_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN new_passed_count INTEGER NOT NULL DEFAULT 0;
