apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alluredeck.api.fullname" . }}
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "alluredeck.api.configYAML" . | indent 4 }}
