{{- if not .Values.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alluredeck.api.fullname" . }}
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
type: Opaque
data:
  SECURITY_ENABLED: {{ .Values.api.security.enabled | b64enc | quote }}
  SECURITY_USER: {{ .Values.api.security.user | b64enc | quote }}
  SECURITY_PASS: {{ (default (randAlphaNum 32) .Values.api.security.password) | b64enc | quote }}
  SECURITY_VIEWER_USER: {{ .Values.api.security.viewerUser | b64enc | quote }}
  SECURITY_VIEWER_PASS: {{ (default (randAlphaNum 32) .Values.api.security.viewerPassword) | b64enc | quote }}
  JWT_SECRET_KEY: {{ (default (randAlphaNum 64) .Values.api.security.jwtSecretKey) | b64enc | quote }}
  JWT_ACCESS_TOKEN_EXPIRES: {{ .Values.api.security.jwtAccessTokenExpires | b64enc | quote }}
  JWT_REFRESH_TOKEN_EXPIRES: {{ .Values.api.security.jwtRefreshTokenExpires | b64enc | quote }}
  {{- if and (eq .Values.api.config.storageType "s3") (not .Values.api.s3.existingSecret) }}
  S3_ACCESS_KEY: {{ .Values.api.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.api.s3.secretKey | b64enc | quote }}
  {{- end }}
{{- end }}
