{{- if not .Values.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alluredeck.api.fullname" . }}
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
type: Opaque
data:
  adminUser: {{ .Values.api.security.user | b64enc | quote }}
  adminPassword: {{ (default (randAlphaNum 32) .Values.api.security.password) | b64enc | quote }}
  viewerUser: {{ .Values.api.security.viewerUser | b64enc | quote }}
  viewerPassword: {{ (default (randAlphaNum 32) .Values.api.security.viewerPassword) | b64enc | quote }}
  jwtSecretKey: {{ (default (randAlphaNum 64) .Values.api.security.jwtSecretKey) | b64enc | quote }}
  jwtAccessTokenExpires: {{ .Values.api.security.jwtAccessTokenExpires | b64enc | quote }}
  jwtRefreshTokenExpires: {{ .Values.api.security.jwtRefreshTokenExpires | b64enc | quote }}
{{- end }}
