apiVersion: v1
kind: Service
metadata:
  name: {{ include "alluredeck.api.fullname" . }}
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http-api
      protocol: TCP
      name: http-api
  selector:
    {{- include "alluredeck.api.selectorLabels" . | nindent 4 }}
{{- if eq (.Values.api.kind | default "Deployment") "StatefulSet" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alluredeck.api.fullname" . }}-headless
  labels:
    {{- include "alluredeck.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http-api
      protocol: TCP
      name: http-api
  selector:
    {{- include "alluredeck.api.selectorLabels" . | nindent 4 }}
{{- end }}
