-- +goose Up
ALTER TABLE builds ADD COLUMN IF NOT EXISTS flaky_count      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS retried_count    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS new_failed_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS new_passed_count INTEGER NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE builds DROP COLUMN IF EXISTS new_passed_count;
ALTER TABLE builds DROP COLUMN IF EXISTS new_failed_count;
ALTER TABLE builds DROP COLUMN IF EXISTS retried_count;
ALTER TABLE builds DROP COLUMN IF EXISTS flaky_count;
