apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alluredeck.ui.fullname" . }}
  labels:
    {{- include "alluredeck.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  revisionHistoryLimit: {{ .Values.ui.revisionHistoryLimit }}
  {{- with .Values.ui.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alluredeck.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/ui/configmap.yaml") . | sha256sum }}
        {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "alluredeck.ui.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "alluredeck.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "alluredeck.ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      {{- with .Values.ui.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.ui.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.ui.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: alluredeck-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http-ui
              containerPort: {{ .Values.ui.service.port | int }}
              protocol: TCP
          env:
            {{- with .Values.ui.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "alluredeck.ui.fullname" . }}
            {{- with .Values.ui.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          {{- with .Values.ui.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- with .Values.ui.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.ui.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.ui.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
